[package]
name = "escimo"
version = "0.1.0"
edition = "2024"

[dependencies]
ascm = { path = "../ascm", features = ["ratatui"] }
clap = { version = "4.6.6", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.30.2"
rfd = "0.17.2"
windows-sys = { version = "0.61.2", features = ["Win32", "Win32_System", "Win32_System_Console"] }
winreg = "0.56.0"

[build-dependencies]
winresource = "0.1"